# Generated by Django 5.0 on 2024-01-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_comment_date_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='posts',
            field=models.ManyToManyField(null=True, related_name='tags_posts', to='blogging.post'),
        ),
    ]
