# Generated by Django 5.0 on 2024-01-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_alter_post_tags_alter_tagging_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blogging.tagging'),
        ),
        migrations.AlterField(
            model_name='tagging',
            name='posts',
            field=models.ManyToManyField(to='blogging.post'),
        ),
    ]
