# Generated by Django 5.0 on 2024-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_alter_post_tags_alter_tagging_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts_tags', to='blogging.tagging'),
        ),
    ]
