# Generated by Django 5.0 on 2024-01-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0010_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_posts', to='blogging.post'),
        ),
    ]
