# Generated by Django 5.0 on 2024-01-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0013_alter_comment_post_remove_post_comment_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
    ]
