# Generated by Django 5.0 on 2024-01-18 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0015_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 18)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(related_name='comments_post', to='blogging.post'),
        ),
    ]
