# Generated by Django 5.0 on 2024-02-01 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0020_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 1)),
        ),
    ]
